require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/provas", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Prova. As you add validations to Prova, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }
  let(:User){
    skip("Add a user")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Prova.create! valid_attributes
      get provas_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      prova = Prova.create! valid_attributes
      get prova_url(prova)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_prova_url
      expect(response).to_not be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      prova = Prova.create! valid_attributes
      get edit_prova_url(prova)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Prova" do
        expect {
          post provas_url, params: { prova: valid_attributes }
        }.to change(Prova, :count).by(1)
      end

      it "redirects to the created prova" do
        post provas_url, params: { prova: valid_attributes }
        expect(response).to redirect_to(prova_url(Prova.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Prova" do
        expect {
          post provas_url, params: { prova: invalid_attributes }
        }.to change(Prova, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post provas_url, params: { prova: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested prova" do
        prova = Prova.create! valid_attributes
        patch prova_url(prova), params: { prova: new_attributes }
        prova.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the prova" do
        prova = Prova.create! valid_attributes
        patch prova_url(prova), params: { prova: new_attributes }
        prova.reload
        expect(response).to redirect_to(prova_url(prova))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        prova = Prova.create! valid_attributes
        patch prova_url(prova), params: { prova: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested prova" do
      prova = Prova.create! valid_attributes
      expect {
        delete prova_url(prova)
      }.to change(Prova, :count).by(-1)
    end

    it "redirects to the provas list" do
      prova = Prova.create! valid_attributes
      delete prova_url(prova)
      expect(response).to redirect_to(provas_url)
    end
  end
end
